export enum ScreenName {
  TabNavigator = "TabNavigator",

  Test = "Test",

  Portal = "Portal",
  PortalAbout = "PortalAbout",
  PortalPolicies = "PortalPolicies",

  Users = "Users",
  UsersBlocking = "UsersBlocking",
  UsersDislikes = "UsersDislikes",
  UsersFollowing = "UsersFollowing",
  UsersLikes = "UsersLikes",
  UsersList = "UsersList",

  Groups = "Groups",
  GroupsBlocking = "GroupsBlocking",
  GroupsDislikes = "GroupsDislikes",
  GroupsFollowing = "GroupsFollowing",
  GroupsLikes = "GroupsLikes",
  GroupsList = "GroupsList",
  GroupsDetail = "GroupsDetail",

  Hashtags = "Hashtags",
  HashtagsBlocking = "HashtagsBlocking",
  HashtagsDislikes = "HashtagsDislikes",
  HashtagsFollowing = "HashtagsFollowing",
  HashtagsLikes = "HashtagsLikes",
  HashtagsList = "HashtagsList",
  HashtagsDetail = "HashtagsDetail",

  Geotags = "Geotags",
  GeotagsBlocking = "GeotagsBlocking",
  GeotagsDislikes = "GeotagsDislikes",
  GeotagsFollowing = "GeotagsFollowing",
  GeotagsLikes = "GeotagsLikes",
  GeotagsList = "GeotagsList",
  GeotagsDetail = "GeotagsDetail",

  Posts = "Posts",
  PostsBlocking = "PostsBlocking",
  PostsDislikes = "PostsDislikes",
  PostsFollowing = "PostsFollowing",
  PostsLikes = "PostsLikes",
  PostsList = "PostsList",
  PostsDetail = "PostsDetail",

  Comments = "Comments",
  CommentsBlocking = "CommentsBlocking",
  CommentsDislikes = "CommentsDislikes",
  CommentsFollowing = "CommentsFollowing",
  CommentsLikes = "CommentsLikes",
  CommentsList = "CommentsList",
  CommentsDetail = "CommentsDetail",

  Timelines = "Timelines",
  TimelinesComments = "TimelinesComments",
  TimelinesGeotagComments = "TimelinesGeotagComments",
  TimelinesGeotagPosts = "TimelinesGeotagPosts",
  TimelinesGroupComments = "TimelinesGroupComments",
  TimelinesGroupPosts = "TimelinesGroupPosts",
  TimelinesHashtagComments = "TimelinesHashtagComments",
  TimelinesHashtagPosts = "TimelinesHashtagPosts",
  TimelinesPosts = "TimelinesPosts",
  TimelinesUserComments = "TimelinesUserComments",
  TimelinesUserPosts = "TimelinesUserPosts",

  Nearby = "Nearby",
  NearbyComments = "NearbyComments",
  NearbyPosts = "NearbyPosts",

  Notifications = "Notifications",

  Conversations = "Conversations",
  ConversationsMessages = "ConversationsMessages",

  Search = "Search",

  ProfileComments = "ProfileComments",
  ProfilePosts = "ProfilePosts",

  ProfileBlockingComments = "ProfileBlockingComments",
  ProfileBlockingGeotags = "ProfileBlockingGeotags",
  ProfileBlockingGroups = "ProfileBlockingGroups",
  ProfileBlockingHashtags = "ProfileBlockingHashtags",
  ProfileBlockingPosts = "ProfileBlockingPosts",
  ProfileBlockingUsers = "ProfileBlockingUsers",

  ProfileDislikesComments = "ProfileDislikesComments",
  ProfileDislikesGeotags = "ProfileDislikesGeotags",
  ProfileDislikesGroups = "ProfileDislikesGroups",
  ProfileDislikesHashtags = "ProfileDislikesHashtags",
  ProfileDislikesPosts = "ProfileDislikesPosts",
  ProfileDislikesUsers = "ProfileDislikesUsers",

  ProfileFollowingComments = "ProfileFollowingComments",
  ProfileFollowingGeotags = "ProfileFollowingGeotags",
  ProfileFollowingGroups = "ProfileFollowingGroups",
  ProfileFollowingHashtags = "ProfileFollowingHashtags",
  ProfileFollowingPosts = "ProfileFollowingPosts",
  ProfileFollowingUsers = "ProfileFollowingUsers",

  ProfileLikesComments = "ProfileLikesComments",
  ProfileLikesGeotags = "ProfileLikesGeotags",
  ProfileLikesGroups = "ProfileLikesGroups",
  ProfileLikesHashtags = "ProfileLikesHashtags",
  ProfileLikesPosts = "ProfileLikesPosts",
  ProfileLikesUsers = "ProfileLikesUsers",

  ProfileInteractionsBlockers = "ProfileInteractionsBlockers",
  ProfileInteractionsDislikers = "ProfileInteractionsDislikers",
  ProfileInteractionsFollowers = "ProfileInteractionsFollowers",
  ProfileInteractionsFollowersYouFollow = "ProfileInteractionsFollowersYouFollow",
  ProfileInteractionsLikers = "ProfileInteractionsLikers",

  Me = "Me",
  MeDrafts = "MeDrafts",
  MeExtCredits = "MeExtCredits",
  MeSetting = "MeSetting",
  MeUsers = "MeUsers",
  MeWallet = "MeWallet",

  Editor = "Editor",

  WebView = "WebView",
}
